### ISSUE TITLE
Daktilo Categories

### ISSUE THREAD

**Issue by dinhvle** [kronik3r/daktilo#3] opened 2015-11-25 21:57 UTC
Explore categories can only display one category even if the post have multiple categories.

**Comment by kronik3r** [comment] 2015-11-28 18:46
Hey @dinhvle! sorry for the late reply, could you please explain more the issue that you've been running into. Thanks!

**Comment by kronik3r** [comment] 2015-11-28 18:49
Because the `Explore` section only shows the categories on your `categories` folder not the ones on your posts. I hope that this will explains your problem :D.

**Comment by dinhvle** [comment] 2015-11-28 20:16
@kronik3r sorry if I wasn't too clear. On the <code>2015-09-06-welcome-to-jekyll.markdown</code> post. There are 2 <code>categories</code>: [design,tool]. If you go to the explore <code>design</code> page, that post will be displayed, however if you go to the explore <code>tool</code> page, that post will not. I'm thinking that if a post have multiple categories, it should be displayed in all those categories. I hope that is more clear. Thanks!

**Comment by kronik3r** [comment] 2015-11-28 22:20
@dinhvle  Don't mind, no problem :). Aha! I see your point now! Thank you for reporting this issue, I'll try to fix that this week-end. Feel free to dig into the code and find a fix I'll be very happy to accept your PR :D.
Cheers!

**Comment by dinhvle** [comment] 2015-11-30 21:34
I'll will try to contribute the best I can, but I just started to learn how to code.  :)

**Comment by kronik3r** [comment] 2015-12-02 22:15
Sorry again for the late reply :D, take your time, dig into the code, write whatever you think can solve the problem, I'll be very happy to review it and suggest improvements :D. We were all staters (and we still). Good luck and enjoy the experience :D.

**Comment by Laevos** [comment] 2015-12-04 17:46
Hi,

I've got some input here; it looks like the problem is specifically with the sample site, not the code itself. Specifically, the code which handles this is the following

> daktilo/_layouts/category.html
> 
> ``` html
>     {% for post in site.posts %}
>         {% if post.categories contains page.category %}
>             <li class="post-teaser">
>                 <a href="{{ post.url | prepend: site.baseurl }}">
>                     <span class="post-teaser__title">{{ post.title }}</span>
>                     <span class="post-teaser__date">{{ post.date | date: "%d %B %Y" }}</span>
>                 </a>
>             </li>
>             {% assign empty_category = false %}
>         {% endif %}
>     {% endfor %}
> ```

This, on my blog, works fine (I can take a post with two categories, and it shows up correctly). I'm not entirely sure, but I think it may have to do with the fact that the sample blog needs to have its _config.yml file updated. If you look carefully at the URLs, you'll see the following when opening the posts themselves:

http://hitchhiker.ma/daktilo//tool/2014/08/19/sample-post.html
http://hitchhiker.ma/daktilo//design/tool/2015/09/06/welcome-to-jekyll.html

See the two trailing slashes after "daktilo"? I think you need to update your baseurl in your _config.yml file to "/daktilo", since it really shouldn't be blank for your sample site. hitchhiker.ma is in a completely different format, and doesn't appear to be the daktilo theme at all. I'm going to fork the project and test out whether updating this fixes the issue.

EDIT: Added kronik3r/daktilo#4

**Comment by dinhvle** [comment] 2015-12-04 22:32
Hahaha, I think the problem is simply a typo. On the blog post the categories is classify as <code>tool</code>. The categories is set up as <code>tools</code>.

**Comment by kronik3r** [comment] 2015-12-14 20:00
@dinhvle @Iggnsthe sorry guys for the late reply again, for your changes(updating _config.yml) they do fix the problem, the only detail that you missed is that the demo website points on the [gh-pages](https://github.com/kronik3r/daktilo/tree/gh-pages) which contains your changes, and don't point on the `master` branch :). But thank you for taking the time and digging info the issue.

Have a nice day guys.

**Comment by kronik3r** [comment] 2015-12-14 20:02
ah and a quick question for you @dinhvle is the problem fixed now :) ??

**Comment by dinhvle** [comment] 2015-12-15 23:49
yeah, problem is fixed, it's just a typo for the post categories.

**Comment by kronik3r** [comment] 2015-12-17 00:08
Cool so I'll close the issue :) it was to nice to talk to you.

**Closed as completed by kronik3r** 2015-12-17 00:08 UTC
